[package]
name = "openapi2mcp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0.99"
clap = "4.5.47"
openapiv3 = "2.2.0"
serde_json = "1.0.143"
serde_yaml = "0.9.34"
