[package]
name = "openapi2mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
openapiv3 = "2.0"
anyhow = "1.0"
convert_case = "0.8"
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.11", features = ["json"] }
url = "2.4"

[dev-dependencies]
tempfile = "3.0"
