name: Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - CLAUDE.md
        - Example documentation
        - Generated code comments
        - CLI help text
        - Code comments
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: Describe the documentation issue
      placeholder: |
        - What documentation is unclear, missing, or incorrect?
        - What specific section or file?
        - What would make it better?
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File path: README.md
        - Section: Installation
        - Line numbers: 45-60

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Provide specific suggestions for improvement

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - New users
        - Experienced users
        - Contributors/developers
        - All users
    validations:
      required: true

  - type: checkboxes
    id: help
    attributes:
      label: Can you help?
      description: Are you willing to help improve this documentation?
      options:
        - label: I can submit a pull request with improvements
        - label: I can review proposed changes
        - label: I can provide more examples
        - label: I can test the documentation with real use cases