openapi: "3.0.0"
info:
  title: "Weather API"
  version: "2.1.0"
  description: "Get weather information for different locations"
  
paths:
  /weather/current:
    get:
      summary: "Get current weather"
      description: "Get current weather conditions for a location"
      operationId: "getCurrentWeather"
      parameters:
        - name: "location"
          in: "query"
          description: "Location to get weather for (city name or coordinates)"
          required: true
          schema:
            type: "string"
            example: "London,UK"
        - name: "units"
          in: "query"
          description: "Temperature units"
          required: false
          schema:
            type: "string"
            enum: ["celsius", "fahrenheit", "kelvin"]
            default: "celsius"
      responses:
        "200":
          description: "Current weather data"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  location:
                    type: "string"
                  temperature:
                    type: "number"
                  humidity:
                    type: "integer"
                  condition:
                    type: "string"
                  windSpeed:
                    type: "number"

  /weather/forecast:
    get:
      summary: "Get weather forecast"
      description: "Get weather forecast for upcoming days"
      operationId: "getWeatherForecast"
      parameters:
        - name: "location"
          in: "query"
          description: "Location to get forecast for"
          required: true
          schema:
            type: "string"
        - name: "days"
          in: "query"
          description: "Number of days to forecast"
          required: false
          schema:
            type: "integer"
            minimum: 1
            maximum: 14
            default: 5
      responses:
        "200":
          description: "Weather forecast data"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  location:
                    type: "string"
                  forecast:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        date:
                          type: "string"
                          format: "date"
                        highTemp:
                          type: "number"
                        lowTemp:
                          type: "number"
                        condition:
                          type: "string"

  /weather/historical:
    get:
      summary: "Get historical weather"
      description: "Get historical weather data for a specific date"
      operationId: "getHistoricalWeather"
      parameters:
        - name: "location"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "date"
          in: "query"
          description: "Date for historical data (YYYY-MM-DD)"
          required: true
          schema:
            type: "string"
            format: "date"
      responses:
        "200":
          description: "Historical weather data"