name: Generate MCP from OpenAPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: cargo test
        run: cargo test

  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24.x

      - name: Setup wash CLI
        uses: wasmcloud/setup-wash-action@47756fa211cc82f392c57e39504f43ef46fc0b3e

      - name: Build component
        uses: wasmcloud/actions/wash-build@v0.2.0

      - name: Install npm dependencies
        run: npm install

      - name: Transpile wasm to JS
        run: npm run build:jco

      - name: Generate MCP from OpenAPI spec
        run: ./scripts/test-e2e.sh
